---
title: "gstream"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Serving Gulf Stream datasets directly from R.

## Requirements

[R v4.1+](https://www.r-project.org/)

[rlang](https://CRAN.R-project.org/package=rlang)

[dplyr](https://CRAN.R-project.org/package=dplyr)

[sf](https://CRAN.R-project.org/package=sf)


## Installation

Use the [remotes](https://CRAN.R-project.org/package=remotes) package to install directly from github.

```         
remotes::install("BigelowLab/gstream)
```

### Data from US Navy

[FTP server](https://ftp.opc.ncep.noaa.gov/grids/experimental/GStream).  A manually prepared dataset that identifies the north wall and south wall as unordered points.  

```{r, warn = FALSE}
suppressPackageStartupMessages({
  library(sf)
  library(dplyr)
  library(gstream)
  library(rnaturalearth)
})

x = read_usn() |>
  dplyr::glimpse()
```

```{r}
bb = sf::st_bbox(x)
coast = rnaturalearth::ne_coastline(scale = "medium", returnclass = "sf")

plot(x['wall'], pch = 3, axes = TRUE, reset = FALSE)
plot(sf::st_geometry(coast), add = TRUE)
```