---
title: "Gulf Stream Width"
author: "B Tupper, J Evanilla"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Gulf Stream Width}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Load the data and select the first data (north and south walls) as an example.

```{r}
suppressPackageStartupMessages({
  library(sf)
  library(dplyr)
  library(gstream)
  library(rnaturalearth)
})
coast = rnaturalearth::ne_coastline(scale = "medium", returnclass = "sf")

All = gstream::read_usn()
bb = sf::st_bbox(All)
x = All |>
  dplyr::slice_max(date)
```


Now make a somewhat arbitrary box.
```{r}
west = -71
east = -61
north = 45
south = 32
BB = sf::st_bbox(c(xmin = west, ymin = south, xmax = east, ymax = north),
                 crs = sf::st_crs(All)) |>
  sf::st_as_sfc()



plot(x['wall'], pch = ".", axes = TRUE, reset = FALSE, extent = BB, key.pos = NULL)
plot(BB, add = TRUE)
plot(sf::st_geometry(coast), add = TRUE)
```



Now we crop the wall data to the box.  Plotted below shows that the lines are both oriented eastward (first point of each plotted with circle symbol.)

```{r, warning = FALSE}
z = st_crop(x, BB) 
p = st_cast(z, "POINT")

plot(z['wall'], reset = FALSE, extent = BB)
plot(p['wall'] |> dplyr::filter(wall == 'north') |> dplyr::slice(1), add = TRUE, col = "black")
plot(p['wall'] |> dplyr::filter(wall == 'south') |> dplyr::slice(1), add = TRUE, col = "black")
plot(sf::st_geometry(coast), add = TRUE)
```


Now merge the two lines into a closed polygon.

```{r, warning = FALSE}
poly = walls_to_polygons(z)


plot(z['wall'], reset = FALSE, extent = BB)
plot(poly[1], add = TRUE)
plot(z['wall'], add = TRUE)
plot(p['wall'] |> dplyr::filter(wall == 'north') |> dplyr::slice(1), add = TRUE, col = "black")
plot(p['wall'] |> dplyr::filter(wall == 'south') |> dplyr::slice(1), add = TRUE, col = "black")
plot(sf::st_geometry(coast), add = TRUE)
```